In [5]:
# import libraries
import requests 
import pandas as pd
import io 
import os 
import numpy as np

In [7]:
# create a variable to store the file path
filepath_istat_data = '../raw/dati_istat.csv'

# create a logic to check if the file exists, if it does, read it into a dataframe, if not, fetch the data from the URL and save it to the file path
if os.path.exists(filepath_istat_data):
    df_istat_data = pd.read_csv(filepath_istat_data)
else:
    url='https://esploradati.istat.it/SDMXWS/rest/data/41_983'
    headers = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        data = response.content.decode('utf-8')
        df_istat_data = pd.read_csv(io.StringIO(data))
        df_istat_data.to_csv(filepath_istat_data, index=False)
    else:
        print(f"Failed to fetch data. Status code: {response.status_code}")

In [11]:
# display the first 5 rows of the dataframe
df_istat_data.head()

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,1001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,1001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,1001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:41_983(1.0),A,1001,KILLINJ,F,2004,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:41_983(1.0),A,1001,KILLINJ,F,2005,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# create a variable to store the file path for the Comuni data
filepath_comuni = '../raw/Comuni - Dimensione Data Indagine 23-06-2026 Stampa 23062026145519.csv'

# create df_comuni to read the Comuni data from the file path
df_comuni = pd.read_csv(filepath_comuni, sep=';')
df_comuni.head()

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
0,1,1,1,201,1001,1001,Agliè,NaN,TO,0,0,2562,2021,"13,1463",2026,2585,2024
1,1,1,1,201,1002,1002,Airasca,NaN,TO,0,0,3660,2021,"15,7393",2026,3695,2024
2,1,1,1,201,1003,1003,Ala di Stura,NaN,TO,0,0,467,2021,"46,3316",2026,463,2024
3,1,1,1,201,1004,1004,Albiano d'Ivrea,NaN,TO,0,0,1637,2021,"11,7397",2026,1624,2024
4,1,1,1,201,1006,1006,Almese,NaN,TO,0,0,6331,2021,"17,8741",2026,6297,2024